### ISSUE TITLE
run_lfqa.sh

### ISSUE THREAD

**Issue by Jason-27** [chaitanyamalaviya/ExpertQA#4]
![image](https://github.com/chaitanyamalaviya/ExpertQA/assets/135086461/445e485d-898f-4a77-92b7-3bc74ae760d8)
This problem occurred when I was running the code, and I don’t know how to solve it for the time being.

**Comment by chaitanyamalaviya** [comment]
Hi @Jason-27 , I think you need to provide those mandatory arguments to run that script. You can see example usage of this script at `bash_scripts/run_lfqa.sh`.
