### ISSUE TITLE
data/r2_compiled_out_corrected_revised_atomic_w_evidences_factscores_anon.jsonl

### ISSUE THREAD

**Issue by Jason-27** [chaitanyamalaviya/ExpertQA#7]
翻译成英语：

Is there any difference between the files `data/r2_compiled_out_corrected_revised_atomic_w_evidences_factscores_anon.jsonl` and `data/r2_compiled_out_corrected_revised_atomic_w_evidences_factscores.jsonl`, or are they essentially the same?
![image](https://github.com/chaitanyamalaviya/ExpertQA/assets/135086461/a4ca6e4e-dd29-4813-8238-c1a14f54a316)

**Comment by chaitanyamalaviya** [comment]
They are the same. The annotator_IDs were anonymized (hence the `anon`) in the file released publicly in this repo.
